file_format: "1"
id: zenboard
name: Zenboard V2
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - zenboard_v2_left
  - zenboard_v2_right
