manifest:
  remotes:
    - name: incptr
      url-base: https://github.com/incptr
  projects:
    - name: zmk
      remote: incptr
      revision: main
      import: app/west.yml
  self:
    path: config
